name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      RunnerId:
        description: enter the run id of latest build
        required: true
        type: text      

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Show RunnerId input
        run: echo "RunnerId is ${{ inputs.RunnerId }}"
